name: Build and Test

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore ImageGc.sln
      working-directory: ./ImageGc
    
    - name: Build
      run: dotnet build ImageGc.sln --configuration Release --no-restore
      working-directory: ./ImageGc
    
    - name: Test
      run: dotnet test ImageGc.sln --configuration Release --no-build --verbosity normal
      working-directory: ./ImageGc
      # Note: This assumes you have test projects in your solution. If not, you can remove this step.
    
    - name: Publish artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: |
          ImageGc/Server/bin/Release/net9.0/publish/
        retention-days: 5
