name: Deploy to Azure

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/build-and-test.yml'
  workflow_run:
    workflows: ["Build and Test"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - uses: actions/checkout@v4
      if: github.event_name != 'workflow_run'
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
      if: github.event_name != 'workflow_run'
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ./publish
      if: github.event_name == 'workflow_run'
    
    - name: Restore dependencies
      run: dotnet restore
      if: github.event_name != 'workflow_run'
    
    - name: Build
      run: dotnet build Server/Server.csproj --configuration Release --no-restore
      if: github.event_name != 'workflow_run'
    
    - name: Publish
      run: dotnet publish Server/Server.csproj --configuration Release --no-build --output ./publish
      if: github.event_name != 'workflow_run'
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PoRedoImage'
        package: ./publish
    
    - name: Configure App Settings
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az webapp config appsettings set --resource-group "PoRedoImage" --name "PoRedoImage" --settings \
            "ComputerVision:Endpoint=${{ secrets.COMPUTER_VISION_ENDPOINT }}" \
            "ComputerVision:Key=${{ secrets.COMPUTER_VISION_KEY }}" \
            "ComputerVision:ApiVersion=2023-10-01" \
            "OpenAI:Endpoint=${{ secrets.OPENAI_ENDPOINT }}" \
            "OpenAI:Key=${{ secrets.OPENAI_KEY }}" \
            "OpenAI:ChatCompletionsDeployment=${{ secrets.OPENAI_CHAT_DEPLOYMENT }}" \
            "OpenAI:ImageGenerationDeployment=${{ secrets.OPENAI_IMAGE_DEPLOYMENT }}" \
            "ApplicationInsights:ConnectionString=${{ secrets.APPINSIGHTS_CONNECTION_STRING }}" \
            "ASPNETCORE_ENVIRONMENT=Production"
    
    - name: Logout from Azure
      run: az logout
      if: always()
