name: Deploy .NET Core App to Azure App Service

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: 'YOUR_AZURE_WEBAPP_NAME'    # Replace with your App Service name
  AZURE_WEBAPP_PACKAGE_PATH: 'Server/publish'   # Set this to the path of your publish directory
  DOTNET_VERSION: '9.x'                         # Set this to the .NET version you are using

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish 'Server/Server.csproj' --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
