name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/build-and-test.yml'
  workflow_run:
    workflows: ["Build and Test"]
    branches: [main]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./ImageGc
        file: ./ImageGc/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/imagegc:latest
          ghcr.io/${{ github.repository_owner }}/imagegc:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
