name: Security Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
          
      - name: Install security scanning tools
        run: |
          dotnet tool install --global dotnet-security-scanner
          
      - name: Run dependency vulnerability scan
        run: |
          cd ImageGc
          dotnet list package --vulnerable --include-transitive
          
      - name: Run SAST scan with CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp
          
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
